### ISSUE TITLE
Gemspec is 0.2.0

### ISSUE THREAD

**Issue by troya2** [platanus/capistrano-lets-encrypt#10]
It appears the Gemspec on rubygems is 0.2.0 and tied to the December 2015 commit, but there are later commits that are needed, including the commit that includes 'colorize' in "lets-encrypt.rake" to allow logging to work.

If I knew the process, I'd make a pull request to update runygems,but alas, I do not 😞

**Comment by thezed** [comment]
bump

**Comment by blackjid** [comment]
wow, sorry, @troya2 I totally missed this issue... I haven't really been using this gem. 

I just published 0.3.0 with the latest commits.
