### ISSUE TITLE
check_certificate doesn't work on OS X

### ISSUE THREAD

**Issue by micred** [platanus/capistrano-lets-encrypt#5]
When I run `cap production lets_encrypt:authorize`

It returns:

```
(Backtrace restricted to imported tasks)
cap aborted!
ArgumentError: unknown command '['

Tasks: TOP => lets_encrypt:authorize
(See full trace by running task with --trace)
```

**Comment by micred** [comment]
It was because lets_encrypt_output_path was not set.

**Comment by blackjid** [comment]
yes, sorry, I just find out that myself.... In the readme is says it has a default.... I should add it...

**Comment by blackjid** [comment]
looks, like it in fact is set by default.. https://github.com/platanus/capistrano-lets-encrypt/blob/master/lib/capistrano/tasks/lets-encrypt.rake#L206
