### ISSUE TITLE
authorize fails

### ISSUE THREAD

**Issue by micred** [platanus/capistrano-lets-encrypt#6]
When I run:
`cap production lets_encrypt:authorize --trace`

I get:
    ...
    2016-03-10 14:30:32 +0100: No certificate found
    2016-03-10 14:30:32 +0100: Authorizing xxxx.
    2016-03-10 14:30:32 +0100: existing account key found
    cap aborted!
    NoMethodError: undefined method `execute' for main:Object
    /Users/michele/.rvm/gems/ruby-2.1.5/gems/capistrano-lets-encrypt-0.2.0/lib/capistrano/tasks/lets-encrypt.rake:85:in`authorize'

**Comment by blackjid** [comment]
I will close this, please open if needed
