### ISSUE TITLE
"Getting started" documentation is missing

### ISSUE THREAD

**Issue by micred** [platanus/capistrano-lets-encrypt#7]
Hi guys, thank you for your great work.
I think that this gem need a "Getting started" section in the README to be more mainstream and to speed up adoption.
### More details in the config parameters
- lets_encrypt_domains must be a string separating domains by a space (it's not written anywhere);
- pretty much all parameters are mandatory;
- at least one server that match the parameter `lets_encrypt_roles` must be set as primary: true, otherwise it exits without notice (#6).
### How to add to the workflow?

What Capistrano task I have to call and when?
In my humble first attempts I matched capistrano-lets-encrypt with capistrano3-nginx. Maybe it's too specific but if you find it useful, I can write a wiki page for that.

**Comment by micred** [comment]
lol, I realized later that even capistrano3-nginx is yours... :-)

**Comment by blackjid** [comment]
could you please make a PR with the changes you consider would help you??

**Comment by blackjid** [comment]
yes, we also use capistrano3-nginx and we pass variables from one to another...
something like this:

``` ruby
# deploy/production.rb

set :nginx_ssl_domains, 'foo.mydomain.com'
set :nginx_domains, 'foo.mydomain.com'

set :nginx_ssl_certificate_path, -> {
  File.join(fetch(:lets_encrypt_output_path), fetch(:nginx_ssl_domains))
}
set :nginx_ssl_certificate_key_path, -> {
  File.join(fetch(:lets_encrypt_output_path), fetch(:nginx_ssl_domains))
}

set :nginx_ssl_certificate, 'fullchain.pem'
set :nginx_ssl_certificate_key, 'key.pem'

set :lets_encrypt_email, 'my@email.com'
set :lets_encrypt_domains, -> { fetch(:nginx_ssl_domains) }
```

> Note: this work only for 1 ssl domain... but would be easy to tweak it

**Comment by blackjid** [comment]
I will close this, please open if needed
